name: Check Markdown and Examples
on: [push, pull_request]
jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        runner: [
            'macos-latest',
            'ubuntu-latest',
            'windows-latest',
        ]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm test
